use us;
CREATE TABLE flights (
 YEAR INT,
 MONTH TINYINT,
 DAY TINYINT,
 DAY_OF_WEEK TINYINT,
 AIRLINE CHAR(2),
 FLIGHT_NUMBER INT,
 TAIL_NUMBER VARCHAR(10),
 ORIGIN_AIRPORT CHAR(3),
 DESTINATION_AIRPORT CHAR(3),
 SCHEDULED_DEPARTURE INT,
 DEPARTURE_TIME INT,
 DEPARTURE_DELAY INT,
 TAXI_OUT INT,
 WHEELS_OFF INT,
 SCHEDULED_TIME INT,
 ELAPSED_TIME INT,
 AIR_TIME INT,
 WHEELS_ON INT,
 TAXI_IN SMALLINT,
 SCHEDULED_ARRIVAL INT,
 ARRIVAL_TIME INT,
 ARRIVAL_DELAY INT,
 DISTANCE INT,
 DIVERTED TINYINT,
 CANCELLED TINYINT,
 CANCELLATION_REASON CHAR(1),
 AIR_SYSTEM_DELAY INT,
 SECURITY_DELAY INT,
 AIRLINE_DELAY INT,
 LATE_AIRCRAFT_DELAY INT,
 WEATHER_DELAY INT
);

SET GLOBAL LOCAL_INFILE=ON;
LOAD DATA LOCAL INFILE 'C:\\temp\\flights.csv' INTO TABLE flights
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

show tables;
select * from flights;

SELECT COUNT(*) AS total_rows
FROM flights;

-- Total cancellations and diversions
SELECT 
    SUM(CANCELLED) AS total_cancelled,
    SUM(DIVERTED) AS total_diverted
FROM flights;

-- Cancellations by reason
SELECT 
	 CANCELLATION_REASON,
     COUNT(*) AS cancellations
FROM flights
WHERE CANCELLED=1
GROUP BY CANCELLATION_REASON;

-- Arrival delay statistics
SELECT 
	AVG(ARRIVAL_DELAY) AS Avg_arrival_delay,
    MAX(ARRIVAL_DELAY) AS max_arrival_delay,
    MIN(ARRIVAL_DELAY) AS min_arrival_delay
FROM flights
WHERE CANCELLED=0 AND ARRIVAL_DELAY IS NOT NULL;

-- Departure delay statistics
SELECT 
	AVG(DEPARTURE_DELAY) AS Avg_departure_delay,
    MAX(DEPARTURE_DELAY) AS max_departure_delay,
    MIN(DEPARTURE_DELAY) AS min_departure_delay
FROM flights
WHERE CANCELLED=0 AND DEPARTURE_DELAY IS NOT NULL;

-- Distribution of Delay Types
SELECT
    SUM(AIRLINE_DELAY) AS airline_delay,
    SUM(WEATHER_DELAY) AS weather_delay,
    SUM(AIR_SYSTEM_DELAY) AS nas_delay,
    SUM(LATE_AIRCRAFT_DELAY) AS late_aircraft_delay,
    SUM(SECURITY_DELAY) AS security_delay
FROM flights;

-- KPI's
-- On-Time Performance (OTP)
SELECT
	ROUND(SUM(CASE WHEN ARRIVAL_DELAY<15 THEN 1 ELSE 0 END)*100/COUNT(*),2) AS otp_rate
FROM flights
WHERE CANCELLED=0;

-- Average Arrival Delay
SELECT 
	AVG(ARRIVAL_DELAY) AS avg_arrival_delay
FROM flights
WHERE CANCELLED=0 AND ARRIVAL_DELAY IS NOT NULL;

-- Average Departure Delay
SELECT 
	AVG(DEPARTURE_DELAY) AS avg_departure_delay
FROM flights
WHERE CANCELLED=0 AND DEPARTURE_DELAY IS NOT NULL;

-- Cancellation Rate
SELECT
	ROUND(SUM(CANCELLED) * 100.0 / COUNT(*),2) AS cancellation_rate
FROM flights;

-- Percentage Contribution of Delay Types
SELECT
	ROUND(SUM(AIRLINE_DELAY)*100.0/
	(SUM(AIRLINE_DELAY)+SUM(WEATHER_DELAY)+SUM(AIR_SYSTEM_DELAY)+SUM(LATE_AIRCRAFT_DELAY)+SUM(SECURITY_DELAY)),2) AS airline_pct,

	ROUND(SUM(WEATHER_DELAY)*100.0/
	(SUM(AIRLINE_DELAY)+SUM(WEATHER_DELAY)+SUM(AIR_SYSTEM_DELAY)+SUM(LATE_AIRCRAFT_DELAY)+SUM(SECURITY_DELAY)),2) AS weather_pct,
    
	ROUND(SUM(AIR_SYSTEM_DELAY)*100.0/
	(SUM(AIRLINE_DELAY)+SUM(WEATHER_DELAY)+SUM(AIR_SYSTEM_DELAY)+SUM(LATE_AIRCRAFT_DELAY)+SUM(SECURITY_DELAY)),2) AS air_system_pct,
    
    ROUND(SUM(LATE_AIRCRAFT_DELAY)*100.0/
	(SUM(AIRLINE_DELAY)+SUM(WEATHER_DELAY)+SUM(AIR_SYSTEM_DELAY)+SUM(LATE_AIRCRAFT_DELAY)+SUM(SECURITY_DELAY)),2) AS late_aircraft_pct,
    
    ROUND(SUM(SECURITY_DELAY)*100.0/
	(SUM(AIRLINE_DELAY)+SUM(WEATHER_DELAY)+SUM(AIR_SYSTEM_DELAY)+SUM(LATE_AIRCRAFT_DELAY)+SUM(SECURITY_DELAY)),2) AS security_pct
FROM flights
WHERE CANCELLED=0;

SELECT
	a.AIRLINE,
    COUNT(*) as total_flights,
    AVG(f.ARRIVAL_DELAY) as avg_arrival_delay
FROM flights f
JOIN airlines a 
ON f.AIRLINE= a.IATA_CODE
WHERE CANCELLED=0 
GROUP BY a.AIRLINE
ORDER BY avg_arrival_delay DESC;

SELECT 
	a.AIRLINE,
	COUNT(*) AS total_flights,
	ROUND(SUM(f.CANCELLED)*100.0/COUNT(*),2) AS cancellation_rate
FROM flights f
JOIN airlines a
ON f.AIRLINE = a.IATA_CODE
GROUP BY a.AIRLINE
ORDER BY cancellation_rate DESC;


SELECT
	ap.AIRPORT,
    ap.CITY,
    COUNT(*) AS flights,
    AVG(f.DEPARTURE_DELAY) AS avg_departure_delay
FROM flights f
JOIN airports ap
ON f.ORIGIN_AIRPORT = ap.IATA_CODE
WHERE CANCELLED = 0
GROUP BY ap.AIRPORT, ap.CITY
ORDER BY flights;

SELECT 
	DAY_OF_WEEK,
	AVG(ARRIVAL_DELAY) AS avg_delay,
	COUNT(*) AS flights
FROM flights
WHERE CANCELLED =0
GROUP BY DAY_OF_WEEK
ORDER BY DAY_OF_WEEK;

SELECT 
	MONTH,
	AVG(ARRIVAL_DELAY) AS avg_delay,
	COUNT(*) AS flights
FROM flights
WHERE CANCELLED =0
GROUP BY MONTH
ORDER BY MONTH;

SELECT 
MONTH,
COUNT(*) AS flights,
SUM(CANCELLED) AS cancellations
FROM flights
GROUP BY MONTH
ORDER BY MONTH;

SELECT
	CASE
    WHEN SCHEDULED_DEPARTURE BETWEEN 0 AND 600 THEN 'Early Morning'
    WHEN SCHEDULED_DEPARTURE BETWEEN 601 AND 1200 THEN 'Morning'
    WHEN SCHEDULED_DEPARTURE BETWEEN 1201 AND 1800 THEN 'Afternoon'
    ELSE 'Evening'
	END AS time_of_day,
	COUNT(*) AS flights,
	AVG(ARRIVAL_DELAY) AS avg_delay
FROM flights
WHERE CANCELLED=0
GROUP BY time_of_day;





